[package]
name = "first-blockchain"
version = "0.1.0"
edition = "2021"
authors = ["Ahiiia92"]

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
chrono = "0.4.38"
datetime = "0.5.2"
serde_json = "1.0.117"
sha2 = "0.10.8"
